server:
  port: 8080
  servlet:
    context-path: /api/v1

spring:
  application:
    name: user-signin-service
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    template:
      exchange: user.exchange
  data:
    mongodb:
      database: users
      host: localhost
      port: 27017