server:
  port: 8081
  servlet:
    context-path: /api/v1

spring:
  application:
    name: new-user-mailing-service
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    template:
      exchange: user.exchange
